[package]
name = "karaoke-audio-win"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
karaoke-protocol = { path = "../protocol" }
karaoke-timeline = { path = "../timeline" }
windows = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
